// TypeScript declarations for window.electronAPI
// This file extends the Window interface to include Electron IPC methods

interface OutputFile {
  name: string
  path: string
  type: 'md' | 'pdf' | 'pptx'
  modified: Date
}

interface BuildResult {
  success: boolean
  outputPath: string
  outputDir: string
  mdPath: string
  htmlPath: string | null
  pdfPath: string | null
}

interface SlideContent {
  filename: string
  content: string
  isCustom: boolean
  originalContent: string
}

interface ElectronAPI {
  // Workshop operations
  getWorkshops: () => Promise<any[]>
  loadWorkshop: (workshopId: string) => Promise<any>
  saveWorkshop: (workshopId: string, config: any) => Promise<boolean>
  createWorkshop: (workshopId: string, config: any) => Promise<boolean>

  // Content library
  getContentLibrary: () => Promise<any[]>
  readSlide: (filePath: string) => Promise<string>

  // Slide content for editor
  getModuleSlides: (moduleId: string, workshopId: string) => Promise<SlideContent[]>
  getTopicSlide: (topicId: string, workshopId: string) => Promise<SlideContent | null>
  getSlideContent: (slideId: string, workshopId: string) => Promise<SlideContent | null>

  // Custom slides
  getCustomSlides: (workshopId: string) => Promise<any[]>
  saveCustomSlide: (workshopId: string, filename: string, content: string) => Promise<boolean>

  // Templates
  getTemplates: () => Promise<Array<{
    id: string
    name: string
    description: string
    templates: Array<{
      id: string
      file: string | null
      name: string
      icon: string
      special?: boolean
      path: string | null
      preview: string
    }>
  }>>

  // Build
  buildDeck: (workshopId: string, skipPdf?: boolean) => Promise<BuildResult>

  // File operations
  openFile: (filePath: string) => Promise<boolean>
  showInFolder: (filePath: string) => Promise<boolean>
  readFileContent: (filePath: string) => Promise<string>
  getOutputsPath: () => Promise<string>
  getWorkshopOutputs: (workshopId: string) => Promise<OutputFile[]>
  openPreviewWindow: (htmlPath: string) => Promise<boolean>

  // AI Assistant
  aiChat: (messages: any[], context: any) => Promise<{
    role: string
    content: string
    toolCalls?: Array<{ id: string; name: string; input: any }>
    stopReason?: string
  }>

  // ═══════════════════════════════════════════════════════════════════════════
  // Native TypeScript Build Pipeline
  // ═══════════════════════════════════════════════════════════════════════════

  // Slide Assembly
  assembleMarkdown: (workshopId: string) => Promise<string>
  assembleJSON: (workshopId: string) => Promise<{
    workshopId: string
    slides: Array<{
      id: string
      title: string
      markdown: string
      meta: {
        dayNumber: number
        sessionName: string
        isBreak?: boolean
        isSection?: boolean
      }
    }>
    totalSlides: number
  }>

  // Time Calculation
  calculateDayTimes: (workshopId: string, dayNumber: number) => Promise<{
    dayNumber: number
    startTime: string
    endTime: string
    sessions: Array<{
      startTime: string
      endTime: string
      duration: number
    }>
    totalDuration: number
  }>
  calculateAllTimes: (workshopId: string) => Promise<Array<{
    dayNumber: number
    startTime: string
    endTime: string
    totalDuration: number
  }>>

  // Auto-generated Content
  generateDayRecap: (workshopId: string, dayNumber: number) => Promise<{
    markdown: string
    title: string
    bullets: string[]
  }>
  generateDayWrapup: (workshopId: string, dayNumber: number) => Promise<{
    markdown: string
    title: string
    bullets: string[]
  }>
  getAutoGeneratedContent: (workshopId: string, dayNumber: number, sessionType: string) => Promise<{
    recap_yesterday?: string
    recap_today?: string
    wrapup_message?: string
  } | null>

  // Export with Progress
  exportDeck: (workshopId: string, format: string) => Promise<{
    success: boolean
    outputPath: string
    format: string
    slideCount?: number
    duration?: number
    error?: string
  }>
  quickBuild: (workshopId: string) => Promise<{
    mdPath: string
    htmlPath: string
  }>
  cancelExport: () => Promise<void>

  // Event Listeners
  onExportProgress: (callback: (progress: {
    stage: string
    progress: number
    message?: string
    error?: string
    totalSlides?: number
  }) => void) => () => void

  onContentChanged: (callback: (data: { file: string }) => void) => () => void
}

declare global {
  interface Window {
    electronAPI: ElectronAPI
  }
}

export {}
