/**
 * SessionEditor Component
 *
 * Modal editor for special session types (Day Recap, Day End)
 * with auto-generation support and live preview.
 */

import { useState, useEffect, useCallback } from 'react'
import { useWorkshopStore, Session } from '../stores/workshop'
import {
  X,
  RefreshCw,
  Sparkles,
  BookOpen,
  Sunset,
  Eye,
  Edit3,
} from 'lucide-react'

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

interface SessionEditorProps {
  session: Session
  sessionIndex: number
  dayNumber: number
  onClose: () => void
  onSave: (updates: Partial<Session>) => void
}

type EditorMode = 'auto' | 'custom'

// ═══════════════════════════════════════════════════════════════════════════════
// SESSION EDITOR COMPONENT
// ═══════════════════════════════════════════════════════════════════════════════

export function SessionEditor({
  session,
  sessionIndex: _sessionIndex,
  dayNumber,
  onClose,
  onSave,
}: SessionEditorProps) {
  const { currentWorkshopId } = useWorkshopStore()

  const [mode, setMode] = useState<EditorMode>('auto')
  const [isLoading, setIsLoading] = useState(false)
  const [autoContent, setAutoContent] = useState<{
    recap_yesterday?: string
    recap_today?: string
    wrapup_message?: string
  } | null>(null)

  // Local state for editable content
  const [recapYesterday, setRecapYesterday] = useState(session.recap_yesterday || '')
  const [recapToday, setRecapToday] = useState(session.recap_today || '')
  const [wrapupMessage, setWrapupMessage] = useState(session.wrapup_message || '')
  const [duration, setDuration] = useState(session.duration || 10)
  const [sessionName, setSessionName] = useState(session.session)

  const isRecap = session.type === 'day_recap'
  const isDayEnd = session.type === 'day_end'

  // Determine initial mode based on content
  useEffect(() => {
    if (isRecap) {
      const hasCustomContent = !!(session.recap_yesterday || session.recap_today)
      setMode(hasCustomContent ? 'custom' : 'auto')
    } else if (isDayEnd) {
      const hasCustomContent = !!session.wrapup_message
      setMode(hasCustomContent ? 'custom' : 'auto')
    }
  }, [session, isRecap, isDayEnd])

  // Fetch auto-generated content
  const fetchAutoContent = useCallback(async () => {
    if (!currentWorkshopId) return

    setIsLoading(true)
    try {
      const content = await window.electronAPI.getAutoGeneratedContent(
        currentWorkshopId,
        dayNumber,
        session.type || ''
      )
      setAutoContent(content)

      // If in auto mode and content was fetched, update local state
      if (mode === 'auto' && content) {
        if (isRecap) {
          setRecapYesterday(content.recap_yesterday || '')
          setRecapToday(content.recap_today || '')
        } else if (isDayEnd) {
          setWrapupMessage(content.wrapup_message || '')
        }
      }
    } catch (err) {
      console.error('Error fetching auto content:', err)
    }
    setIsLoading(false)
  }, [currentWorkshopId, dayNumber, session.type, mode, isRecap, isDayEnd])

  // Fetch on mount and mode change
  useEffect(() => {
    if (mode === 'auto') {
      fetchAutoContent()
    }
  }, [mode, fetchAutoContent])

  // Handle mode switch
  const handleModeChange = (newMode: EditorMode) => {
    setMode(newMode)

    if (newMode === 'auto' && autoContent) {
      // Reset to auto-generated content
      if (isRecap) {
        setRecapYesterday(autoContent.recap_yesterday || '')
        setRecapToday(autoContent.recap_today || '')
      } else if (isDayEnd) {
        setWrapupMessage(autoContent.wrapup_message || '')
      }
    }
  }

  // Handle save
  const handleSave = () => {
    const updates: Partial<Session> = {
      session: sessionName,
      duration,
    }

    if (isRecap) {
      if (mode === 'auto') {
        // Clear custom content to trigger auto-generation
        updates.recap_yesterday = ''
        updates.recap_today = ''
      } else {
        updates.recap_yesterday = recapYesterday
        updates.recap_today = recapToday
      }
    } else if (isDayEnd) {
      if (mode === 'auto') {
        updates.wrapup_message = ''
      } else {
        updates.wrapup_message = wrapupMessage
      }
    }

    onSave(updates)
    onClose()
  }

  // Regenerate auto content
  const handleRegenerate = () => {
    fetchAutoContent()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className={`px-6 py-4 flex items-center justify-between ${
          isRecap ? 'bg-blue-50 border-b border-blue-200' : 'bg-orange-50 border-b border-orange-200'
        }`}>
          <div className="flex items-center gap-3">
            {isRecap ? (
              <BookOpen className="w-5 h-5 text-blue-500" />
            ) : (
              <Sunset className="w-5 h-5 text-orange-500" />
            )}
            <div>
              <h2 className={`text-lg font-semibold ${
                isRecap ? 'text-blue-800' : 'text-orange-800'
              }`}>
                {isRecap ? 'Edit Day Recap' : 'Edit Day End'}
              </h2>
              <p className={`text-sm ${isRecap ? 'text-blue-600' : 'text-orange-600'}`}>
                Day {dayNumber}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-white/50 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[calc(90vh-180px)]">
          {/* Session Name & Duration */}
          <div className="flex items-center gap-4 mb-6">
            <div className="flex-1">
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Session Name
              </label>
              <input
                type="text"
                value={sessionName}
                onChange={e => setSessionName(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-fastr-primary focus:border-transparent"
              />
            </div>
            <div className="w-24">
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Duration
              </label>
              <div className="flex items-center gap-1">
                <input
                  type="number"
                  value={duration}
                  onChange={e => setDuration(parseInt(e.target.value) || 0)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-fastr-primary focus:border-transparent text-center"
                />
                <span className="text-sm text-gray-500">min</span>
              </div>
            </div>
          </div>

          {/* Mode Toggle */}
          <div className="flex items-center gap-2 mb-4 p-1 bg-gray-100 rounded-lg w-fit">
            <button
              onClick={() => handleModeChange('auto')}
              className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-colors ${
                mode === 'auto'
                  ? 'bg-white text-fastr-primary shadow'
                  : 'text-gray-600 hover:text-gray-800'
              }`}
            >
              <Sparkles className="w-4 h-4" />
              Auto-generate
            </button>
            <button
              onClick={() => handleModeChange('custom')}
              className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-colors ${
                mode === 'custom'
                  ? 'bg-white text-fastr-primary shadow'
                  : 'text-gray-600 hover:text-gray-800'
              }`}
            >
              <Edit3 className="w-4 h-4" />
              Custom
            </button>
          </div>

          {/* Auto-generate info */}
          {mode === 'auto' && (
            <div className={`mb-4 p-4 rounded-lg ${
              isRecap ? 'bg-blue-50 text-blue-700' : 'bg-orange-50 text-orange-700'
            }`}>
              <div className="flex items-start gap-2">
                <Sparkles className="w-4 h-4 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="text-sm font-medium">
                    Content will be auto-generated from your schedule
                  </p>
                  <p className="text-sm opacity-80 mt-1">
                    {isRecap
                      ? "The recap will list yesterday's topics and today's planned sessions."
                      : "The wrap-up will summarize today's sessions and preview tomorrow."}
                  </p>
                </div>
              </div>
              <button
                onClick={handleRegenerate}
                disabled={isLoading}
                className="mt-3 flex items-center gap-2 px-3 py-1.5 bg-white rounded-md text-sm font-medium hover:bg-gray-50 transition-colors"
              >
                <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
                Regenerate Preview
              </button>
            </div>
          )}

          {/* Content Editor */}
          {isRecap && (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Yesterday we covered:
                </label>
                <textarea
                  value={recapYesterday}
                  onChange={e => setRecapYesterday(e.target.value)}
                  disabled={mode === 'auto'}
                  placeholder="- Topic 1&#10;- Topic 2&#10;- Topic 3"
                  rows={4}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent ${
                    mode === 'auto'
                      ? 'bg-gray-50 border-gray-200 text-gray-600'
                      : 'bg-white border-gray-300'
                  }`}
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Today we will cover:
                </label>
                <textarea
                  value={recapToday}
                  onChange={e => setRecapToday(e.target.value)}
                  disabled={mode === 'auto'}
                  placeholder="- Topic 1&#10;- Topic 2&#10;- Topic 3"
                  rows={4}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent ${
                    mode === 'auto'
                      ? 'bg-gray-50 border-gray-200 text-gray-600'
                      : 'bg-white border-gray-300'
                  }`}
                />
              </div>
            </div>
          )}

          {isDayEnd && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Wrap-up Message:
              </label>
              <textarea
                value={wrapupMessage}
                onChange={e => setWrapupMessage(e.target.value)}
                disabled={mode === 'auto'}
                placeholder="Custom message or leave empty for auto-generated content"
                rows={6}
                className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-transparent ${
                  mode === 'auto'
                    ? 'bg-gray-50 border-gray-200 text-gray-600'
                    : 'bg-white border-gray-300'
                }`}
              />
              <p className="mt-1 text-xs text-gray-500">
                {mode === 'auto'
                  ? "Auto-generates 'See You Tomorrow' with next day's start time and session preview"
                  : 'Enter custom markdown content for the wrap-up slide'}
              </p>
            </div>
          )}

          {/* Preview */}
          {(recapYesterday || recapToday || wrapupMessage) && (
            <div className="mt-6">
              <div className="flex items-center gap-2 mb-2">
                <Eye className="w-4 h-4 text-gray-500" />
                <span className="text-sm font-medium text-gray-700">Preview</span>
              </div>
              <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                <div className="prose prose-sm max-w-none">
                  {isRecap && (
                    <>
                      {recapYesterday && (
                        <>
                          <h4 className="text-blue-700 font-semibold">Yesterday we covered:</h4>
                          <ul className="text-gray-700">
                            {recapYesterday.split('\n').filter(l => l.trim()).map((line, i) => (
                              <li key={i}>{line.replace(/^[-*]\s*/, '')}</li>
                            ))}
                          </ul>
                        </>
                      )}
                      {recapToday && (
                        <>
                          <h4 className="text-blue-700 font-semibold mt-3">Today we will cover:</h4>
                          <ul className="text-gray-700">
                            {recapToday.split('\n').filter(l => l.trim()).map((line, i) => (
                              <li key={i}>{line.replace(/^[-*]\s*/, '')}</li>
                            ))}
                          </ul>
                        </>
                      )}
                    </>
                  )}
                  {isDayEnd && wrapupMessage && (
                    <div className="text-gray-700 whitespace-pre-wrap">
                      {wrapupMessage}
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 flex items-center justify-end gap-3">
          <button
            onClick={onClose}
            className="px-4 py-2 text-gray-600 hover:text-gray-800 font-medium transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleSave}
            className={`px-6 py-2 rounded-lg font-medium text-white transition-colors ${
              isRecap
                ? 'bg-blue-500 hover:bg-blue-600'
                : 'bg-orange-500 hover:bg-orange-600'
            }`}
          >
            Save Changes
          </button>
        </div>
      </div>
    </div>
  )
}

export default SessionEditor
