import { useState, useEffect, useMemo } from 'react'
import { Loader2, GitFork } from 'lucide-react'
import { Session, useWorkshopStore } from '../../stores/workshop'
import { t } from '../../i18n/translations'
import { workshopAPI } from '../../../lib/api'
import { useToast } from '../../components/Toast'
import { Modal } from '../../components/ui/Modal'
import { Button } from '../../components/ui/Button'
import { Input } from '../../components/ui/Input'
import { Select } from '../../components/ui/Select'
import { Textarea } from '../../components/ui/Textarea'
import { Field } from '../../components/ui/Field'

interface EditSessionModalProps {
  session: Session
  dayNum: number
  totalDays: number
  onClose: () => void
  onSave: (updates: Partial<Session>) => void
  onDelete: () => void
  onMoveToDay: (toDay: number) => void
}

// Computed slides (day1_agenda, day2_recap, etc.) are generated by the server;
// their source is the workshop config, not a markdown file. Not forkable.
const COMPUTED_SLIDE_RE = /^day\d+_(agenda|recap)$/

export function EditSessionModal({
  session,
  dayNum,
  totalDays,
  onClose,
  onSave,
  onDelete,
  onMoveToDay,
}: EditSessionModalProps) {
  const { contentLanguage, currentWorkshopId } = useWorkshopStore()
  const { showToast } = useToast()
  const [sessionName, setSessionName] = useState(session.session || '')
  const [speaker, setSpeaker] = useState(session.speaker || '')
  const [duration, setDuration] = useState(session.duration || 0)
  const [moveToDay, setMoveToDay] = useState<number | null>(null)

  // Classify the slide reference. We only show the markdown editor for
  // single-slide sessions where the slide is either already a per-workshop
  // custom slide (editable in place) or a library slide we can fork.
  const { slideRef, isCustom, isForkable } = useMemo(() => {
    const ref = session.slides?.[0]
    if (!ref || (session.slides?.length ?? 0) !== 1) {
      return { slideRef: null, isCustom: false, isForkable: false }
    }
    if (session.type === 'section' || session.type === 'break' || session.type === 'day_title'
        || session.type === 'day_end' || session.type === 'day_recap') {
      return { slideRef: null, isCustom: false, isForkable: false }
    }
    if (COMPUTED_SLIDE_RE.test(ref)) {
      return { slideRef: null, isCustom: false, isForkable: false }
    }
    if (ref.startsWith('custom_slides/')) {
      return { slideRef: ref, isCustom: true, isForkable: false }
    }
    return { slideRef: ref, isCustom: false, isForkable: true }
  }, [session.slides, session.type])

  const [slideContent, setSlideContent] = useState('')
  const [slideLoading, setSlideLoading] = useState(false)
  const [slideSaving, setSlideSaving] = useState(false)
  const [slideDirty, setSlideDirty] = useState(false)
  // Filename to save under: for custom, the existing filename; for forkable,
  // the bare library filename (which becomes custom_slides/<filename>.md after save).
  const saveFilename = useMemo(() => {
    if (!slideRef) return null
    return isCustom ? slideRef.slice('custom_slides/'.length) : slideRef
  }, [slideRef, isCustom])

  // Load the markdown when the modal opens for an editable session.
  useEffect(() => {
    if (!slideRef || !currentWorkshopId) return
    let cancelled = false
    setSlideLoading(true)
    workshopAPI
      .getSlideContent(currentWorkshopId, slideRef, contentLanguage)
      .then(res => {
        if (cancelled) return
        setSlideContent(res.content || '')
      })
      .catch(err => {
        if (!cancelled) showToast(`Failed to load slide content: ${err.message}`, 'error')
      })
      .finally(() => { if (!cancelled) setSlideLoading(false) })
    return () => { cancelled = true }
  }, [slideRef, currentWorkshopId, contentLanguage, showToast])

  const handleSave = async () => {
    // If this session has an editable slide and the markdown changed,
    // persist that first. On forkable slides, also repoint session.slides.
    const slidesUpdate: { slides?: string[] } = {}
    if (slideRef && saveFilename && currentWorkshopId && slideDirty) {
      setSlideSaving(true)
      try {
        await workshopAPI.saveCustomSlide(currentWorkshopId, saveFilename, slideContent)
        if (isForkable) {
          // Repoint this session's slide at the new per-workshop copy.
          slidesUpdate.slides = [`custom_slides/${saveFilename}`]
          showToast('Library slide forked for this workshop', 'success')
        } else {
          showToast('Slide content saved', 'success')
        }
      } catch (err: any) {
        showToast(`Slide save failed: ${err.message}`, 'error')
        setSlideSaving(false)
        return // keep modal open so user can retry
      }
      setSlideSaving(false)
    }

    onSave({
      session: sessionName,
      speaker: speaker || undefined,
      duration,
      ...slidesUpdate,
    })
    onClose()
  }

  const handleDelete = () => {
    if (confirm(t('confirmDeleteSession', contentLanguage))) {
      onDelete()
      onClose()
    }
  }

  const showSlideEditor = isCustom || isForkable

  return (
    <Modal
      open
      onClose={onClose}
      title={t('sessionSettings', contentLanguage)}
      size="md"
      footer={
        <div className="flex w-full items-center justify-between">
          <Button variant="ghost" onClick={handleDelete} className="text-red-600 hover:bg-red-50">
            {t('deleteSession', contentLanguage)}
          </Button>
          <div className="flex gap-2">
            <Button variant="secondary" onClick={onClose}>
              {t('cancel', contentLanguage)}
            </Button>
            <Button variant="primary" onClick={handleSave} disabled={slideLoading || slideSaving}>
              {slideSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : null}
              {t('saveChanges', contentLanguage)}
            </Button>
          </div>
        </div>
      }
    >
      <div className="space-y-4">
        <Field label={t('sessionName', contentLanguage)} htmlFor="es-name">
          <Input
            id="es-name"
            type="text"
            value={sessionName}
            onChange={e => setSessionName(e.target.value)}
            placeholder={t('sessionName', contentLanguage)}
          />
        </Field>

        <Field label={t('facilitatorPresenter', contentLanguage)} htmlFor="es-speaker">
          <Input
            id="es-speaker"
            type="text"
            value={speaker}
            onChange={e => setSpeaker(e.target.value)}
            placeholder="e.g., John Smith, MoH Team"
          />
        </Field>

        <Field label={t('durationMinutes', contentLanguage)} htmlFor="es-duration">
          <Input
            id="es-duration"
            type="number"
            value={duration}
            onChange={e => setDuration(parseInt(e.target.value) || 0)}
            min={0}
            step={5}
          />
        </Field>

        {showSlideEditor && (
          <Field
            label={t(isForkable ? 'forkAndEdit' : 'editSlideMarkdown', contentLanguage)}
            htmlFor="es-slide-content"
            hint={t(isForkable ? 'forkAndEditHint' : 'editSlideMarkdownHint', contentLanguage)}
          >
            {isForkable && (
              <div className="mb-2 flex items-start gap-2 rounded-md bg-amber-50 border border-amber-200 px-3 py-2 text-caption text-amber-900">
                <GitFork className="w-4 h-4 mt-0.5 flex-shrink-0" />
                <span>{t('forkBanner', contentLanguage)}</span>
              </div>
            )}
            {slideLoading ? (
              <div className="flex items-center gap-2 text-body-sm text-slate-500 py-2">
                <Loader2 className="w-4 h-4 animate-spin" />
                {t('forking', contentLanguage)}
              </div>
            ) : (
              <Textarea
                id="es-slide-content"
                value={slideContent}
                onChange={e => { setSlideContent(e.target.value); setSlideDirty(true) }}
                rows={10}
                className="font-mono text-caption"
                spellCheck={false}
              />
            )}
          </Field>
        )}

        {totalDays > 1 && (
          <Field label={t('moveToDifferentDay', contentLanguage)} htmlFor="es-move">
            <div className="flex gap-2">
              <Select
                id="es-move"
                value={moveToDay ?? ''}
                onChange={e => setMoveToDay(e.target.value ? parseInt(e.target.value) : null)}
                className="flex-1"
              >
                <option value="">{t('selectDay', contentLanguage)}</option>
                {Array.from({ length: totalDays }, (_, i) => i + 1)
                  .filter(d => d !== dayNum)
                  .map(d => (
                    <option key={d} value={d}>
                      {t('day', contentLanguage)} {d}
                    </option>
                  ))}
              </Select>
              <Button
                variant="secondary"
                onClick={() => {
                  if (moveToDay) {
                    onMoveToDay(moveToDay)
                    onClose()
                  }
                }}
                disabled={!moveToDay}
              >
                {t('move', contentLanguage)}
              </Button>
            </div>
          </Field>
        )}
      </div>
    </Modal>
  )
}
