#!/usr/bin/env python3
"""
Generate CATALOG.md — a single, clear index of all FASTR content.

Sources (single sources of truth):
  - modules.yaml                     modules, themes, activity metadata
  - core_content/<folder>/_meta.yaml per-module slide counts (full/condensed)
  - handouts/_order.yaml             curated handout sets per module

Run:  python3 tools/generate_catalog.py
This regenerates CATALOG.md — do NOT edit CATALOG.md by hand.
"""
import os
import yaml
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(rel):
    p = os.path.join(ROOT, rel)
    return yaml.safe_load(open(p, encoding='utf-8')) if os.path.exists(p) else None


def slide_counts(folder):
    meta = load(f'core_content/{folder}/_meta.yaml') or {}
    c = Counter(s.get('variant', 'full') for s in meta.get('slides', []))
    return c.get('full', 0), c.get('condensed', 0)


def fr_exists(folder):
    return os.path.isdir(os.path.join(ROOT, 'core_content_fr', folder))


def main():
    reg = load('modules.yaml')
    modules = reg['modules']
    order = load('handouts/_order.yaml') or {}

    out = []
    out.append('# FASTR content catalog\n')
    out.append('> Generated by `tools/generate_catalog.py` from `modules.yaml`, the per-module '
               '`_meta.yaml`, and `handouts/_order.yaml`. **Do not edit by hand — re-run the tool.**\n')

    active = [m for m in modules if not m.get('deprecated')]
    total_full = sum(slide_counts(m['folder'])[0] for m in active)
    total_cond = sum(slide_counts(m['folder'])[1] for m in active)
    n_acts = sum(1 for m in modules if (m.get('ai_context') or {}).get('activity'))
    out.append(f'**{len(active)} active modules** · **{total_full} full + {total_cond} condensed slides** · '
               f'**{n_acts} activities** · slides + handouts in EN + FR\n')

    # ── Modules ────────────────────────────────────────────────────────────
    out.append('## Modules\n')
    out.append('| # | id | Module | Theme | Full | Condensed | Status |')
    out.append('|---|----|--------|-------|-----:|----------:|--------|')
    for m in modules:
        full, cond = slide_counts(m['folder'])
        status = '🚫 deprecated' if m.get('deprecated') else 'active'
        out.append(f"| {m['number']} | `{m['id']}` | {m['name']['en']} | {m.get('theme', '')} "
                   f"| {full or '—'} | {cond or '—'} | {status} |")

    # ── Activities (logical order) ─────────────────────────────────────────
    acts = sorted(
        ((m['ai_context']['activity'].get('order', 99), m) for m in modules
         if (m.get('ai_context') or {}).get('activity')),
        key=lambda x: x[0])
    out.append('\n## Activities — logical order\n')
    out.append('Each activity has a deck, handouts (participant), and a facilitator guide. '
               'Prerequisites form a dependency chain.\n')
    out.append('| Order | Activity | Prereq | Duration | Covers |')
    out.append('|------:|----------|--------|----------|--------|')
    for o, m in acts:
        a = m['ai_context']['activity']
        ai = m['ai_context']
        pre = ', '.join(a.get('prerequisites') or []) or '—'
        out.append(f"| {o} | **{m['name']['en']}** (`{m['id']}`) | {pre} | {ai.get('duration', '')} "
                   f"| {a.get('covers', '')} |")

    # ── Handouts (by module) ───────────────────────────────────────────────
    out.append('\n## Handouts — by module (EN + FR)\n')
    for key in sorted(order, key=lambda k: (len(k), k)):
        items = order[key] or []
        names = [h for h in items]
        out.append(f'\n**`{key}`** — {len(names)} handout(s)')
        for h in names:
            label = '_(facilitator guide)_' if 'facilitator' in h else ''
            out.append(f'- `{h}` {label}'.rstrip())

    open(os.path.join(ROOT, 'CATALOG.md'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    print(f'Wrote CATALOG.md — {len(active)} modules, {n_acts} activities, {len(order)} handout sets')


if __name__ == '__main__':
    main()
