import { contextBridge, ipcRenderer } from 'electron'

// Expose protected methods to the renderer process
contextBridge.exposeInMainWorld('electronAPI', {
  // Workshop operations
  getWorkshops: () => ipcRenderer.invoke('get-workshops'),
  loadWorkshop: (workshopId: string) => ipcRenderer.invoke('load-workshop', workshopId),
  saveWorkshop: (workshopId: string, config: any) => ipcRenderer.invoke('save-workshop', workshopId, config),
  createWorkshop: (workshopId: string, config: any) => ipcRenderer.invoke('create-workshop', workshopId, config),

  // Content library (legacy)
  getContentLibrary: () => ipcRenderer.invoke('get-content-library'),
  readSlide: (filePath: string) => ipcRenderer.invoke('read-slide', filePath),

  // Parsed content (structured JSON)
  getParsedContent: () => ipcRenderer.invoke('get-parsed-content'),
  getParsedModule: (moduleId: string) => ipcRenderer.invoke('get-parsed-module', moduleId),
  getParsedTopic: (topicId: string) => ipcRenderer.invoke('get-parsed-topic', topicId),
  getParsedSlide: (topicId: string, slideIndex: number) => ipcRenderer.invoke('get-parsed-slide', topicId, slideIndex),
  refreshContent: () => ipcRenderer.invoke('refresh-content'),

  // Content change listener
  onContentChanged: (callback: (data: { file: string }) => void) => {
    ipcRenderer.on('content-changed', (_event, data) => callback(data))
    return () => ipcRenderer.removeAllListeners('content-changed')
  },

  // Slide content for editor
  getModuleSlides: (moduleId: string, workshopId: string) =>
    ipcRenderer.invoke('get-module-slides', moduleId, workshopId),
  getTopicSlide: (topicId: string, workshopId: string) =>
    ipcRenderer.invoke('get-topic-slide', topicId, workshopId),
  getSlideContent: (slideId: string, workshopId: string) =>
    ipcRenderer.invoke('get-slide-content', slideId, workshopId),

  // Custom slides
  getCustomSlides: (workshopId: string) => ipcRenderer.invoke('get-custom-slides', workshopId),
  saveCustomSlide: (workshopId: string, filename: string, content: string) =>
    ipcRenderer.invoke('save-custom-slide', workshopId, filename, content),

  // Templates
  getTemplates: () => ipcRenderer.invoke('get-templates'),

  // Build
  buildDeck: (workshopId: string, skipPdf?: boolean) => ipcRenderer.invoke('build-deck', workshopId, skipPdf),

  // File operations
  openFile: (filePath: string) => ipcRenderer.invoke('open-file', filePath),
  showInFolder: (filePath: string) => ipcRenderer.invoke('show-in-folder', filePath),
  readFileContent: (filePath: string) => ipcRenderer.invoke('read-file-content', filePath),
  getOutputsPath: () => ipcRenderer.invoke('get-outputs-path'),
  getWorkshopOutputs: (workshopId: string) => ipcRenderer.invoke('get-workshop-outputs', workshopId),
  openPreviewWindow: (htmlPath: string) => ipcRenderer.invoke('open-preview-window', htmlPath),

  // AI Assistant
  aiChat: (messages: any[], context: any) => ipcRenderer.invoke('ai-chat', messages, context),
  aiGenerateText: (prompt: string, context?: any) => ipcRenderer.invoke('ai-generate-text', prompt, context),

  // ═══════════════════════════════════════════════════════════════════════════
  // NEW: Native TypeScript Build Pipeline
  // ═══════════════════════════════════════════════════════════════════════════

  // Slide Assembly
  assembleMarkdown: (workshopId: string) => ipcRenderer.invoke('assemble-markdown', workshopId),
  assembleJSON: (workshopId: string) => ipcRenderer.invoke('assemble-json', workshopId),

  // Time Calculation
  calculateDayTimes: (workshopId: string, dayNumber: number) =>
    ipcRenderer.invoke('calculate-day-times', workshopId, dayNumber),
  calculateAllTimes: (workshopId: string) =>
    ipcRenderer.invoke('calculate-all-times', workshopId),

  // Auto-generated Content
  generateDayRecap: (workshopId: string, dayNumber: number) =>
    ipcRenderer.invoke('generate-day-recap', workshopId, dayNumber),
  generateDayWrapup: (workshopId: string, dayNumber: number) =>
    ipcRenderer.invoke('generate-day-wrapup', workshopId, dayNumber),
  getAutoGeneratedContent: (workshopId: string, dayNumber: number, sessionType: string) =>
    ipcRenderer.invoke('get-auto-generated-content', workshopId, dayNumber, sessionType),

  // Export with Progress
  exportDeck: (workshopId: string, format: string) =>
    ipcRenderer.invoke('export-deck', workshopId, format),
  quickBuild: (workshopId: string) =>
    ipcRenderer.invoke('quick-build', workshopId),
  cancelExport: () => ipcRenderer.invoke('cancel-export'),

  // Export Progress Events
  onExportProgress: (callback: (progress: any) => void) => {
    ipcRenderer.on('export-progress', (_event, progress) => callback(progress))
    return () => ipcRenderer.removeAllListeners('export-progress')
  },
})

// TypeScript declarations for window.electronAPI
declare global {
  // Parsed content types
  interface SlideElement {
    type: 'heading' | 'text' | 'bullet' | 'numbered' | 'image' | 'code' | 'directive'
    content: string
    level?: number
    alt?: string
    src?: string
    language?: string
  }

  interface ParsedSlide {
    index: number
    title: string
    elements: SlideElement[]
    rawContent: string
    layout?: string
  }

  interface ParsedTopic {
    id: string
    file: string
    title: string
    path: string
    slides: ParsedSlide[]
    frontmatter: Record<string, any>
    slideCount: number
    lastModified: number
  }

  interface ParsedModule {
    number: number
    id: string
    name: string
    folder: string
    topics: ParsedTopic[]
    totalSlides: number
  }

  interface ParsedContentResult {
    modules: ParsedModule[]
    lastUpdated: number
  }

  interface SlideContent {
    filename: string
    content: string
    isCustom: boolean
    originalContent: string
  }

  interface Window {
    electronAPI: {
      // Workshop operations
      getWorkshops: () => Promise<any[]>
      loadWorkshop: (workshopId: string) => Promise<any>
      saveWorkshop: (workshopId: string, config: any) => Promise<boolean>
      createWorkshop: (workshopId: string, config: any) => Promise<boolean>

      // Content library (legacy)
      getContentLibrary: () => Promise<any[]>
      readSlide: (filePath: string) => Promise<string>

      // Parsed content (structured JSON)
      getParsedContent: () => Promise<ParsedContentResult>
      getParsedModule: (moduleId: string) => Promise<ParsedModule | null>
      getParsedTopic: (topicId: string) => Promise<ParsedTopic | null>
      getParsedSlide: (topicId: string, slideIndex: number) => Promise<ParsedSlide | null>
      refreshContent: () => Promise<ParsedContentResult>
      onContentChanged: (callback: (data: { file: string }) => void) => () => void

      // Slide content for editor
      getModuleSlides: (moduleId: string, workshopId: string) => Promise<SlideContent[]>
      getTopicSlide: (topicId: string, workshopId: string) => Promise<SlideContent | null>
      getSlideContent: (slideId: string, workshopId: string) => Promise<SlideContent | null>

      // Custom slides
      getCustomSlides: (workshopId: string) => Promise<any[]>
      saveCustomSlide: (workshopId: string, filename: string, content: string) => Promise<boolean>

      // Templates
      getTemplates: () => Promise<any[]>

      // Build
      buildDeck: (workshopId: string, skipPdf?: boolean) => Promise<{
        success: boolean
        output: string
        outputPath: string
        outputDir: string
        mdPath: string
        htmlPath: string | null
        pdfPath: string | null
      }>

      // File operations
      openFile: (filePath: string) => Promise<boolean>
      showInFolder: (filePath: string) => Promise<boolean>
      readFileContent: (filePath: string) => Promise<string>
      getOutputsPath: () => Promise<string>
      getWorkshopOutputs: (workshopId: string) => Promise<Array<{
        name: string
        path: string
        type: 'md' | 'pdf' | 'pptx'
        modified: Date
      }>>
      openPreviewWindow: (htmlPath: string) => Promise<boolean>

      // AI Assistant
      aiChat: (messages: any[], context: any) => Promise<{ role: string; content: string; toolCalls?: any[] }>
      aiGenerateText: (prompt: string, context?: any) => Promise<string>

      // ═══════════════════════════════════════════════════════════════════════════
      // NEW: Native TypeScript Build Pipeline
      // ═══════════════════════════════════════════════════════════════════════════

      // Slide Assembly
      assembleMarkdown: (workshopId: string) => Promise<string>
      assembleJSON: (workshopId: string) => Promise<{
        workshopId: string
        slides: Array<{
          id: string
          title: string
          markdown: string
          meta: {
            dayNumber: number
            sessionName: string
            isBreak?: boolean
            isSection?: boolean
          }
        }>
        totalSlides: number
      }>

      // Time Calculation
      calculateDayTimes: (workshopId: string, dayNumber: number) => Promise<{
        dayNumber: number
        startTime: string
        endTime: string
        sessions: Array<{
          startTime: string
          endTime: string
          duration: number
        }>
        totalDuration: number
      }>
      calculateAllTimes: (workshopId: string) => Promise<Array<{
        dayNumber: number
        startTime: string
        endTime: string
        totalDuration: number
      }>>

      // Auto-generated Content
      generateDayRecap: (workshopId: string, dayNumber: number) => Promise<{
        markdown: string
        title: string
        bullets: string[]
      }>
      generateDayWrapup: (workshopId: string, dayNumber: number) => Promise<{
        markdown: string
        title: string
        bullets: string[]
      }>
      getAutoGeneratedContent: (workshopId: string, dayNumber: number, sessionType: string) => Promise<{
        recap_yesterday?: string
        recap_today?: string
        wrapup_message?: string
      } | null>

      // Export with Progress
      exportDeck: (workshopId: string, format: string) => Promise<{
        success: boolean
        outputPath: string
        format: string
        slideCount?: number
        duration?: number
        error?: string
      }>
      quickBuild: (workshopId: string) => Promise<{
        mdPath: string
        htmlPath: string
      }>
      cancelExport: () => Promise<void>

      // Export Progress Events
      onExportProgress: (callback: (progress: {
        stage: string
        progress: number
        message?: string
        error?: string
        totalSlides?: number
      }) => void) => () => void
    }
  }
}
